name: generated

on:
  - push
  - pull_request

jobs:
  atlas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Hash migrations
        run: devbox run migrate:hash

      - name: Make sure all changes generated
        run: echo 'ci_migration' | devbox run migrate:diff

      - name: Ensure no changes
        run: git diff --exit-code

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Run generation tasks
        run: devbox run generate

      - name: Ensure no changes
        run: git diff --exit-code
